FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Guía funcionamiento del Callback

Esta guía provee información detallada acerca de los funcionamientos estándar del callback al momento de ejecutar un pago.

# Group Procesos

## Llamada estándar
    
**Paso 1**: Al realizar un pago se dispara el evento por el cual se extrae la información del mismo y se procede a la firma de los datos más importantes, que luego serán enviados al comercio.

**Paso 2**: Una vez realizada la firma de los datos por MYMOID, la información es enviada al comercio a través del
método "POST" a la URL de destino designada en el momento del registro del mismo.


## Llamada de error
    
**Paso 1**: En el momento en que se intenta realizar el pago y este es denegado se dispara el evento al igual que en una llamada estándar, con la diferencia que en este caso el mensaje y el código del error son incluidos en la firma
realizada por MYMOID (ver listado de errores en "[Guía códigos de error MYMOID](https://github.com/rlop03/MYMOID/wiki/C%C3%B3digos-de-error-MYMOID-API-Doc)").

**Paso 2**: El método de envío es el mismo que en la llamada estándar.


# Group Política de reintentos  
## Llamada estándar
    
**Paso 1**: MYMOID tiene establecida una política de tres intentos en el caso de que el pago realizado no se encuentre
aún en la base de datos, si el pago no es encontrado la firma y envío del callback no es realizado.  

**Paso 2**: Una vez realizada la firma correspondiente de los datos el callback es enviado. En caso de que la respuesta del servidor externo (Cliente) sea distinta a ‘status = 200’ MYMOID es notificado y el proceso es terminado; si no es posible realizar el método de envío por parte de MYMOID este es almacenado en cola de envío, para ser enviado cuando el funcionamiento correcto de MYMOID sea restablecido.


## Llamada de error
    
**Paso 1**: Al producir el error de pago no es necesario almacenarlo en la base de datos como un pago realizado, por lo cual en caso de error el callback seria enviado inmediatamente sin reintentos.

**Paso 2**: La configuración del envío de callback de error es la misma que para una llamada estándar.


# Group Listado de posibles errores recibidos
**Mensaje**: Error authenticating paymentMethod.   
**Código**: Validator.mymoPay.paymentMethodAuthenticationError

**Mensaje**: Operation not allowed for external merchant. Trade should contact the processing center to solve the problem.  
**Código**: Validator.mymoPay.operationNotAllowedForExternalMerchant.

**Mensaje**: Gateway system error. Try in a few minutes  
**Código**: Validator.mymoPay.gatewayServiceError

**Mensaje**: This payment method has expired  
**Código**: Validator.mymoPay.paymentMethodExpired

**Mensaje**: Amount too small for this transaction  
**Código**: Validator.mymoPay.amountTooSmall

**Mensaje**: Invalid card number  
**Código**: Validator.invalidCardNumber

**Mensaje**: Error authenticating paymentMethod  
**Código**: Validator.mymoPay.paymentMethodAuthenticationError

**Mensaje**: Operation not allowed for this payment method, use another  
**Código**: Validator.mymoPay.paymentMethodNotValid

**Mensaje**: Payment order is not available  
**Código**: Validator.mymoPay.paymentOrderUnavailable

**Mensaje**: We cannot process payment because a problem on Gateway  
**Código**: Validator.mymoPay.gatewayError